services:
  - type: web
    name: vape-shop
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /buyer
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vape-shop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
